### ISSUE TITLE
Decide on a form framework

### ISSUE THREAD

**Issue by Capure** [bajton/bajton#39]
Decide which form framework to use and add it to the project.
The decision should be based on solid arguments and consulted with the team.

**Comment by Aruturuu** [comment]
### **_Form Framework Council (FFC)_ decided on using _react-hook-form_.**

There were two competitors consisting of _**Formik**_ and _**react-hook-form**_.

Janitor decided to formalize a quick summary explaining our choice.
- Some members of the council tried both frameworks and found _**react-hook-form**_ to be easier to use. This may be because of simplicity of said framework, as it is much more ligthweight than _**Formik**_.
- The _**react-hook-form**_ displays better performance regarding load times and amount of re-renders.
- It also has slightly more stars on github with comparable amount of projects using it, it is not a significant argument.
